network:
  hidden_layer_sizes: [5, 10]
  # hidden_layer_sizes: [1000, 1000, 1000]
  activation: "relu"
  solver: "adam"
  batch_size: 400
  max_iter: 2000
  random_state: 0

training:
  n_samples: 400
  random_state: 0

visualization:
  x_range: [-1.5, 1.5]
  y_range: [-1.5, 1.5]
  grid_resolution: 400
